# Kamal deployment configuration for Stormgate World Discord Bot

service: stormgate-discord-bot

# Server(s) to deploy to
servers:
  web:
    hosts:
      - 147.189.173.240
    proxy: false
  

# Docker image
image: stormgate-world-discord

# Build arguments and secrets
builder:
  arch: amd64

# Environment variables (loaded from .env on deploy machine)
env:
  secret:
    - CLIENT_ID
    - TOKEN
    - PREFIX

retain_containers: 1

registry:
  server: localhost:5555